# Generated by Django 5.1.3 on 2025-01-05 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicio', '0002_detalleventa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productoretornable',
            name='estado',
            field=models.CharField(choices=[('Disponible', 'Disponible'), ('Ocupado', 'Ocupado'), ('Dañado', 'Dañado')], default='Disponible', max_length=50),
        ),
        migrations.AlterField(
            model_name='venta',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
