# Generated by Django 5.1.3 on 2025-03-14 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicio', '0003_alter_productoretornable_estado_alter_venta_fecha'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='venta',
            options={'ordering': ['-fecha']},
        ),
        migrations.RenameField(
            model_name='divisionempleado',
            old_name='nombre',
            new_name='ruta',
        ),
    ]
