# Generated by Django 5.1.3 on 2025-03-16 17:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicio', '0004_alter_venta_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductonoRetornable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.IntegerField(default=0)),
                ('tipo_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicio.tipoproducto')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProductosiRetornable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descripcion', models.CharField(max_length=30)),
                ('estado', models.CharField(choices=[('Disponible', 'Disponible'), ('Ocupado', 'Ocupado'), ('Dañado', 'Dañado')], default='Disponible', max_length=50)),
                ('tipo_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicio.tipoproducto')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RegistroVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('anticipo', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('saldo_pendiente', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicio.cliente')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicio.empleado')),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='RegistroDetalleVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(blank=True, default=1, null=True)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('producto_no_retornable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='servicio.productonoretornable')),
                ('producto_retornable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='servicio.productosiretornable')),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='servicio.registroventa')),
            ],
        ),
    ]
