# Generated by Django 5.1.3 on 2025-03-17 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicio', '0005_productonoretornable_productosiretornable_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrodetalleventa',
            name='cantidad',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
