# Generated by Django 5.1.3 on 2025-03-17 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicio', '0006_alter_registrodetalleventa_cantidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='registroventa',
            name='deuda_anterior',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
