# Generated by Django 5.1.3 on 2025-03-21 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicio', '0008_location_ruta'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='productos',
            field=models.ManyToManyField(blank=True, to='servicio.productosiretornable'),
        ),
    ]
