# Generated by Django 5.1.3 on 2025-03-22 16:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicio', '0010_remove_empleado_productos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrodetalleventa',
            name='producto_retornable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='servicio.productosiretornable'),
        ),
    ]
