# Generated by Django 5.1.3 on 2025-03-22 16:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicio', '0011_alter_registrodetalleventa_producto_retornable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrodetalleventa',
            name='producto_retornable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='servicio.productosiretornable'),
        ),
    ]
